---

- name: Generate the password
  shell:
    cmd: vault write -field=value gen/password length=32 symbols=0
  environment:
    VAULT_TOKEN: "{{ vault_keys.administrative.root_token }}"
  changed_when: false
  no_log: true
  register: __vault_secrets__new_password

- fail:
    msg: The password hasn\'t been generated
  when: __vault_secrets__new_password.stdout | length == 0

- name: "Store the password to the {{ result }} fact" 
  set_fact:
    "{{ result }}": "{{ __vault_secrets__new_password.stdout }}"
  no_log: true