---

- name: "Look up for the {{ token[0] }} token"
  set_fact:
    __vault_tokens__token_from_policies: >-
      {{
        token[1]
      }}
    __vault_tokens__token_from_globals: >-
      {{
        (
          token[0] in vault_tokens and
          vault_tokens[token[0]] is defined and
          vault_tokens[token[0]] is mapping
        ) | ternary(
          vault_tokens[token[0]],
          {}
        )
      }}

- name: "Determine weight of {{ token[0] }} token"
  set_fact:
    __vault_tokens__token_from_policies: >-
      {{
        __vault_tokens__token_from_policies | combine(
          {
            'weight': (
              'weight' in __vault_tokens__token_from_policies and
              __vault_tokens__token_from_policies.weight is defined
            ) | ternary(
              __vault_tokens__token_from_policies.weight,
              0
            )
          }
        )
      }}
    __vault_tokens__token_from_globals: >-
      {{
        __vault_tokens__token_from_globals | combine(
          {
            'weight': (
              'weight' in __vault_tokens__token_from_globals and
              __vault_tokens__token_from_globals.weight is defined
            ) | ternary(
              __vault_tokens__token_from_globals.weight,
              0
            )
          }
        )
      }}

- name: "Add the policy name to the {{ token[0] }} token"
  set_fact:
    __vault_tokens__token_from_policies: >-
      {{
        __vault_tokens__token_from_policies | combine(
          {
            'policies': [ policy ]
          }
        )
      }}

- name: "Merge the {{ token[0] }} token into the global tokens list"
  set_fact:
    vault_tokens: >-
      {{
        vault_tokens
          | default([])
          | combine(
            {
              token[0]:
                (__vault_tokens__token_from_policies.weight | int == -1) | ternary(
                  __vault_tokens__token_from_policies,
                  (__vault_tokens__token_from_globals.weight | int == -1) | ternary(
                    __vault_tokens__token_from_globals,
                    (__vault_tokens__token_from_policies.weight | int >= __vault_tokens__token_from_globals.weight | int) | ternary(
                      __vault_tokens__token_from_globals | combine(__vault_tokens__token_from_policies, list_merge='append_rp', recursive=true),
                      __vault_tokens__token_from_policies | combine(__vault_tokens__token_from_globals, list_merge='append_rp', recursive=true)
                    )
                  )
                )
            }
          )
      }}

#- pause:
#    prompt: "{{ vault_tokens | to_nice_yaml }}"