---

- name: Check if the policy is mapping
  fail:
    msg: "The policy is not mapping"
  when: policy_to_setup[1] is not mapping

- name: Render the policy as a HCL file
  template:
    src: "policy.hcl.j2"
    dest: "{{ vault_directory_policies }}/{{ policy_to_setup[0] }}.hcl"
  vars:
    policy_name: "{{ policy_to_setup[0] }}"
    policy: "{{ policy_to_setup[1] }}"

- name: Apply the policy
  command:
    cmd: >-
      vault
      policy
      write
      {{ policy_to_setup[0] }}
      {{ vault_directory_policies }}/{{ policy_to_setup[0] }}.hcl
  environment:
    VAULT_TOKEN: "{{ vault_keys.administrative.root_token }}"
  no_log: true # Change it to true later

- name: Add the policy to the tokens
  include_tasks: add_token.yaml
  vars:
    policy: "{{ policy_to_setup[0] }}"
  loop: "{{ policy_to_setup[1]['tokens'] | items }}"
  loop_control:
    loop_var: token
  when: >-
    'tokens' in policy_to_setup[1] and
    policy_to_setup[1]['tokens'] is defined and
    policy_to_setup[1]['tokens'] is iterable